### ISSUE TITLE
Can't find package in Atom package installer

### ISSUE THREAD

**Issue by proehlen** [coffutt/atom-jsdoc#34]
Have tried searching for `jsdoc` and `atom-jsdoc`.  

I'm using Atom version 1.0.5

I want to use this package but don't know how to install it.

**Comment by lightinen** [comment]
No avalible package for this version with trying install by apm. Please, update package to latest atom build.

**Comment by jpsmith1981** [comment]
I would like this as well unless anyone knows of an alternative plugin?

**Comment by proehlen** [comment]
@jpsmit1981 I'm using https://atom.io/packages/docblockr now.  So far so good.

**Comment by amovah** [comment]
I Have same problem.
